# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cbSize = QtWidgets.QComboBox(self.centralwidget)
        self.cbSize.setEditable(False)
        self.cbSize.setObjectName("cbSize")
        self.cbSize.addItem("")
        self.cbSize.addItem("")
        self.cbSize.addItem("")
        self.gridLayout.addWidget(self.cbSize, 0, 4, 1, 1)
        self.cbProperty = QtWidgets.QComboBox(self.centralwidget)
        self.cbProperty.setObjectName("cbProperty")
        self.cbProperty.addItem("")
        self.cbProperty.addItem("")
        self.cbProperty.addItem("")
        self.gridLayout.addWidget(self.cbProperty, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pbBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.pbBrowse.setObjectName("pbBrowse")
        self.gridLayout.addWidget(self.pbBrowse, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.sbTE = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbTE.setObjectName("sbTE")
        self.gridLayout.addWidget(self.sbTE, 0, 6, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gvDecay = PlotWidget(self.tab)
        self.gvDecay.setObjectName("gvDecay")
        self.gridLayout_2.addWidget(self.gvDecay, 0, 0, 1, 1)
        self.gvRecovery = PlotWidget(self.tab)
        self.gvRecovery.setObjectName("gvRecovery")
        self.gridLayout_2.addWidget(self.gvRecovery, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblImage = QtWidgets.QLabel(self.tab_2)
        self.lblImage.setText("")
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.gridLayout_7.addWidget(self.lblImage, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 5, 2, 8)
        self.sbTR = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbTR.setObjectName("sbTR")
        self.gridLayout.addWidget(self.sbTR, 0, 7, 1, 1)
        self.sbFA = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbFA.setMaximum(359.99)
        self.sbFA.setObjectName("sbFA")
        self.gridLayout.addWidget(self.sbFA, 0, 8, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblPhantom = QtWidgets.QLabel(self.centralwidget)
        self.lblPhantom.setBaseSize(QtCore.QSize(0, 128))
        self.lblPhantom.setText("")
        self.lblPhantom.setScaledContents(True)
        self.lblPhantom.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhantom.setObjectName("lblPhantom")
        self.gridLayout_5.addWidget(self.lblPhantom, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 103, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 1, 2, 4)
        self.sbGraphs = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.sbGraphs.setObjectName("sbGraphs")
        self.gridLayout.addWidget(self.sbGraphs, 0, 12, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cbSize.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cbSize.setStatusTip(_translate("MainWindow", "Phantom size"))
        self.cbSize.setCurrentText(_translate("MainWindow", "128"))
        self.cbSize.setItemText(0, _translate("MainWindow", "128"))
        self.cbSize.setItemText(1, _translate("MainWindow", "256"))
        self.cbSize.setItemText(2, _translate("MainWindow", "512"))
        self.cbProperty.setStatusTip(_translate("MainWindow", "Tissue property"))
        self.cbProperty.setItemText(0, _translate("MainWindow", "T1"))
        self.cbProperty.setItemText(1, _translate("MainWindow", "T2"))
        self.cbProperty.setItemText(2, _translate("MainWindow", "PD"))
        self.pbBrowse.setText(_translate("MainWindow", "Browse"))
        self.sbTE.setStatusTip(_translate("MainWindow", "TE"))
        self.gvDecay.setStatusTip(_translate("MainWindow", "Decay curve"))
        self.gvRecovery.setStatusTip(_translate("MainWindow", "Recovery curve"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "D/R Curves"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Image"))
        self.sbTR.setStatusTip(_translate("MainWindow", "TR"))
        self.sbFA.setStatusTip(_translate("MainWindow", "FA"))
        self.sbGraphs.setStatusTip(_translate("MainWindow", "Graphs time span"))

from pyqtgraph import PlotWidget
