# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TASK_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Tabs(object):
    def setupUi(self, Tabs):
        Tabs.setObjectName("Tabs")
        Tabs.resize(875, 674)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pbBrowse1 = QtWidgets.QPushButton(self.tab)
        self.pbBrowse1.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.pbBrowse1.setObjectName("pbBrowse1")
        self.cbPhantomSize_2 = QtWidgets.QComboBox(self.tab)
        self.cbPhantomSize_2.setGeometry(QtCore.QRect(170, 40, 73, 22))
        self.cbPhantomSize_2.setObjectName("cbPhantomSize_2")
        self.cbTissueProberty_2 = QtWidgets.QComboBox(self.tab)
        self.cbTissueProberty_2.setGeometry(QtCore.QRect(320, 40, 73, 22))
        self.cbTissueProberty_2.setObjectName("cbTissueProberty_2")
        self.sbTE_2 = QtWidgets.QSpinBox(self.tab)
        self.sbTE_2.setGeometry(QtCore.QRect(480, 40, 42, 22))
        self.sbTE_2.setObjectName("sbTE_2")
        self.sbTR_2 = QtWidgets.QSpinBox(self.tab)
        self.sbTR_2.setGeometry(QtCore.QRect(570, 40, 42, 22))
        self.sbTR_2.setObjectName("sbTR_2")
        self.sbFlipAngle_2 = QtWidgets.QSpinBox(self.tab)
        self.sbFlipAngle_2.setGeometry(QtCore.QRect(670, 40, 42, 22))
        self.sbFlipAngle_2.setObjectName("sbFlipAngle_2")
        self.sbTimeSpan_2 = QtWidgets.QSpinBox(self.tab)
        self.sbTimeSpan_2.setGeometry(QtCore.QRect(760, 40, 42, 22))
        self.sbTimeSpan_2.setObjectName("sbTimeSpan_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(190, 200, 431, 201))
        self.label_2.setObjectName("label_2")
        Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pbBrowse2 = QtWidgets.QPushButton(self.tab_2)
        self.pbBrowse2.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.pbBrowse2.setObjectName("pbBrowse2")
        self.pbPlotRecovery = QtWidgets.QPushButton(self.tab_2)
        self.pbPlotRecovery.setGeometry(QtCore.QRect(120, 40, 93, 28))
        self.pbPlotRecovery.setObjectName("pbPlotRecovery")
        self.pbPlotDecay = QtWidgets.QPushButton(self.tab_2)
        self.pbPlotDecay.setGeometry(QtCore.QRect(230, 40, 93, 28))
        self.pbPlotDecay.setObjectName("pbPlotDecay")
        self.cbPhantomSize = QtWidgets.QComboBox(self.tab_2)
        self.cbPhantomSize.setGeometry(QtCore.QRect(360, 40, 73, 22))
        self.cbPhantomSize.setObjectName("cbPhantomSize")
        self.cbTissueProberty = QtWidgets.QComboBox(self.tab_2)
        self.cbTissueProberty.setGeometry(QtCore.QRect(480, 40, 73, 22))
        self.cbTissueProberty.setObjectName("cbTissueProberty")
        self.sbTE = QtWidgets.QSpinBox(self.tab_2)
        self.sbTE.setGeometry(QtCore.QRect(590, 40, 42, 22))
        self.sbTE.setObjectName("sbTE")
        self.sbTR = QtWidgets.QSpinBox(self.tab_2)
        self.sbTR.setGeometry(QtCore.QRect(660, 40, 42, 22))
        self.sbTR.setObjectName("sbTR")
        self.sbFlipAngle = QtWidgets.QSpinBox(self.tab_2)
        self.sbFlipAngle.setGeometry(QtCore.QRect(730, 40, 42, 22))
        self.sbFlipAngle.setObjectName("sbFlipAngle")
        self.sbTimeSpan = QtWidgets.QSpinBox(self.tab_2)
        self.sbTimeSpan.setGeometry(QtCore.QRect(790, 40, 42, 22))
        self.sbTimeSpan.setObjectName("sbTimeSpan")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(340, 120, 241, 131))
        self.label.setObjectName("label")
        self.RecoveryGraph = QtWidgets.QGraphicsView(self.tab_2)
        self.RecoveryGraph.setGeometry(QtCore.QRect(10, 310, 371, 301))
        self.RecoveryGraph.setObjectName("RecoveryGraph")
        self.DecayGraph = QtWidgets.QGraphicsView(self.tab_2)
        self.DecayGraph.setGeometry(QtCore.QRect(470, 310, 371, 301))
        self.DecayGraph.setObjectName("DecayGraph")
        Tabs.addTab(self.tab_2, "")

        self.retranslateUi(Tabs)
        Tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Tabs)

    def retranslateUi(self, Tabs):
        _translate = QtCore.QCoreApplication.translate
        Tabs.setWindowTitle(_translate("Tabs", "TabWidget"))
        self.pbBrowse1.setText(_translate("Tabs", "Browse"))
        self.label_2.setText(_translate("Tabs", "TextLabel"))
        Tabs.setTabText(Tabs.indexOf(self.tab), _translate("Tabs", "Tab 1"))
        self.pbBrowse2.setText(_translate("Tabs", "Browse"))
        self.pbPlotRecovery.setText(_translate("Tabs", "Plot Recovery"))
        self.pbPlotDecay.setText(_translate("Tabs", "Plot Decay"))
        self.label.setText(_translate("Tabs", "TextLabel"))
        Tabs.setTabText(Tabs.indexOf(self.tab_2), _translate("Tabs", "Tab 2"))

